/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        forest: '#145A32',
        leaf: '#2E7D32',
        fresh: '#74B816',
        youngleaf: '#9CCC65',
        earth: '#5D4037',
        sand: '#E8F5E9',
        naturewhite: '#F9FFF9',
        skymist: '#BFE8F5',
        river: '#84D6F4',
        fog: '#EDF7F3',
        foresttext: '#123524',
        mistgrey: '#E2ECE6',
        success: '#43A047',
        amber: '#F9A825',
        forestblack: '#081C15',
        jungle: '#0F2D24',
        canopy: '#1B4332',
        leafaccent: '#74C69D',
        skyglow: '#6EDFF6',
        carddark: '#10261F',
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', '"DM Serif Display"', '"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'Inter', 'Manrope', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        organic: '46% 54% 58% 42% / 48% 42% 58% 52%',
        'organic-2': '62% 38% 46% 54% / 44% 58% 42% 56%',
        leaf: '0 50% 0 50%',
      },
      boxShadow: {
        glow: '0 0 40px -8px rgba(116,184,22,.45)',
        'glow-lg': '0 0 80px -12px rgba(116,184,22,.5)',
        night: '0 0 60px -12px rgba(116,198,157,.35)',
      },
      keyframes: {
        sway: { '0%,100%': { transform: 'rotate(-6deg) translateY(0)' }, '50%': { transform: 'rotate(6deg) translateY(-10px)' } },
        drift: { '0%': { transform: 'translate3d(-10vw,0,0)' }, '100%': { transform: 'translate3d(110vw,-6vh,0)' } },
        fall: { '0%': { transform: 'translateY(-10vh) rotate(0deg)', opacity: '0' }, '10%': { opacity: '1' }, '100%': { transform: 'translateY(110vh) rotate(340deg)', opacity: '0' } },
        floaty: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-14px)' } },
        twinkle: { '0%,100%': { opacity: '.15' }, '50%': { opacity: '1' } },
        ripple: { '0%': { transform: 'scale(.6)', opacity: '.8' }, '100%': { transform: 'scale(2.4)', opacity: '0' } },
        growvine: { '0%': { strokeDashoffset: '600' }, '100%': { strokeDashoffset: '0' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        flyAcross: { '0%': { transform: 'translateX(-15vw) translateY(0)' }, '50%': { transform: 'translateX(50vw) translateY(-30px)' }, '100%': { transform: 'translateX(115vw) translateY(10px)' } },
      },
      animation: {
        sway: 'sway 6s ease-in-out infinite',
        drift: 'drift 26s linear infinite',
        fall: 'fall 14s linear infinite',
        floaty: 'floaty 5s ease-in-out infinite',
        twinkle: 'twinkle 3s ease-in-out infinite',
        fly: 'flyAcross 22s linear infinite',
      },
    },
  },
  plugins: [],
};
